accelerate launch --num_processes=1 train_scr.py \
    --seed=123 \
    --data_root="./thesis-data-png" \
    --report_to="wandb" \
    --experience_name="SCR-INTRA" \
    --max_train_steps=210000 \
    --ckpt_interval=20000 \
    --batch_size=16 \
    --learning_rate=1e-4 \
    --loss_mode=intra \
    --save_dir="./scr_ckpts" \
    --resume_ckpt "./scr_ckpts/step_20000.pth"